services:
  django:
    build:
      context: .
      dockerfile: ./config/django_image/Dockerfile
    
    image: videobackend:0.1
    
    container_name: django_backend_container
    
    working_dir: /usr/src/app
    
    volumes:
      - ./src/django:/usr/src/app
      
    ports:
      - "8000:8000"

    # --- INICIO DE CAMBIOS (Video 10) ---
    
    # Le decimos a Django que lea las variables del .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432 # Puerto INTERNO que Django usa para hablar con Postgres
      DJANGO_SUPERUSER_NAME: ${DJANGO_SUPERUSER_NAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    
    # Le decimos que no arranque HASTA QUE el servicio 'postgres' esté listo
    depends_on:
      - postgres
      
    # Mantenemos tu red 'django-net'
    networks:
      - django-net
      
  # --- SERVICIO NUEVO (Video 10) ---
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432" # Expone el puerto de tu .env (15432)
    volumes:
      - ./data:/var/lib/postgresql/data/
    # Hacemos que Postgres se una a TU red
    networks:
      - django-net

# Mantenemos tu definición de red
networks:
  django-net:
    driver: bridge